server {
  listen 80;
  listen [::]:80;
  server_name ancientherbs.ac.cn 107.148.176.151;

  root /var/www/ancientherbs.ac.cn/current;
  index index.html;

  access_log /var/log/nginx/ancientherbs.ac.cn.access.log;
  error_log /var/log/nginx/ancientherbs.ac.cn.error.log warn;

  location /assets/ {
    expires 30d;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
